version: '3.8'

services:
  backend:
    build: ./contact-routing-system/backend
    container_name: banking-contact-backend
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./contact-routing-system/models:/app/models
      - ./contact-routing-system/data:/app/data
      - ./contact-routing-system/logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
    networks:
      - app-network

  frontend:
    build:
      context: ./contact-routing-system/frontend
      dockerfile: Dockerfile
    container_name: banking-contact-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
